name: Lesson 6

on:
  push:
    branches:
      - lesson-6
jobs:
  function_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Run functional tests
        run: npm test -- --coverage --watchAll=false
  deploy:
    needs: [function_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
      - name: Generate deployment package
        run: zip -r deploy.zip build Dockerfile
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
  security_test:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Dynamic Application Security Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'https://hangryhippo.quantic.host'
  acceptance_test:
    needs: [deploy]
    runs-on: ubuntu-latest
    container: cypress/included:10.3.0
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start CRA server
        run: CI=true BROWSER=none npm start &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: cypress run --config-file=cypress.config.js

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cypress-videos
          path: cypress/videos
       